# reusable workflow that builds docker image and optionally pushes it to registry
on:

  workflow_dispatch:
    
  push:
    branches:
      - master


jobs:
  build:
    runs-on: self-hosted
    name: Build image
    outputs:
      image_tag: ${{ env.commit_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "commit_sha=$calculatedSha" >> $GITHUB_ENV

      - name: Set commit and environment
        id: set-vars
        run: |
          echo "commit_sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Artifactory
        uses: docker/login-action@v3
        with:
          registry: hub.emburse.tech
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: prod # artifactory requires prod target for all images regardless of the environment
          tags: hub.emburse.tech/docker/emburse/celery-exporter:${{ env.commit_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
